### ISSUE TITLE
Pri 1: figure out how to install azcopy on Travis 

### ISSUE THREAD

**Issue by saroup** [great-lakes/project-egypt#25]

**Comment by saroup** [comment]
linked to #8

**Comment by saroup** [comment]
Seems like I will switch over from azcopy and use python instead:

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?toc=%2Fen-us%2Fazure%2Fmachine-learning%2Fteam-data-science-process%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json

**Comment by in4margaret** [comment]
Ubuntu 14.04: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=/azure/storage/blobs/toc.json
