### ISSUE TITLE
Create Generator JavaScript  template

### ISSUE THREAD

**Issue by gcrev93** [great-lakes/project-egypt#3]
- Create formalized template of what a generator.js file should like 
i.e. Include name, parameters, and outputs 
- Please include MANDATORY comment section to explain the generator file
- Keep in mind generator file must have a function that can be called from simulated device but also a way to populate the generators info page
- Use this template to create built in generators
- Upload blank generator.js file to repo as standard template for users to pull down and create custom generators

Parent Issue: #20

**Comment by gcrev93** [comment]
Yes agreed .. but all (builtin and custom) should have a set format. thats why i want to make a set template so that all generator files will follow it, even the built in ones we create @saroup

**Comment by kevinleung23** [comment]
Create in Generator Repo: #28

**Comment by gcrev93** [comment]
finished and completed in Generator Rep.  Pull request link below:

https://github.com/great-lakes/project-egypt-generators/pull/1
