### ISSUE TITLE
Create Blob Storage Account & CDN on Azure

### ISSUE THREAD

**Issue by gcrev93** [great-lakes/project-egypt#6]
Parent issue: #21 
- Create a blob container that will be used to store contents of the site
- Create CDN account on Azure
- Link CDN and Blob Container
- Use this [link](https://blog.lifeishao.com/2017/05/24/serving-your-static-sites-with-azure-blob-and-cdn/) for reference
- Blob will be linked to Travis, and rewritten with each update to code (only in master)
Using Azure CLI

**Comment by gcrev93** [comment]
Blob storage is used to host the web page not store data from the device @saroup

**Comment by saroup** [comment]
@gcrev93 The first bullet point mentions that the storage is to store contents of the device. Can you adjust this description to mention that it is used to host the web page?

**Comment by gcrev93** [comment]
Sorry! thank you for catching that @saroup

**Comment by in4margaret** [comment]
Commands to create resources with AzureCLI:

az login 

az account set --subscription SUBSCRIPTION_ID

az group create --name GROUP_NAME --location REGION

az storage account create --kind BlobStorage --name STORAGE_NAME --resource-group GROUP_NAME --location REGION --access-tier Hot

az cdn profile create --name PROFILE_NAME -g GROUP_NAME -l REGION

az cdn endpoint create -g gl_GROUP_NAME -l eastus  --name ENDPOINT_NAME --profile-name PROFILE_NAME --origin STORAGE_NAME.blob.core.windows.net --origin-host-header STORAGE_NAME.blob.core.windows.net
