### ISSUE TITLE
CDN endpoint: rerouting the main website page

### ISSUE THREAD

**Issue by saroup** [great-lakes/project-egypt#60]
Right now we need to put index.html to access the website. Let's reroute this so we don't have to put index.html explicitly

**Comment by dwcares** [comment]
works on mybox

**Comment by dwcares** [comment]
this is a CDN issue

**Comment by in4margaret** [comment]
@dwcares, yes, we just don't want to specify index.html each time for our endpoint.
I already added rules for CDN

**Comment by in4margaret** [comment]
Issues with creating CDN  Premium tier
