### ISSUE TITLE
Setup Travis link to Blob Storage & CDN

### ISSUE THREAD

**Issue by gcrev93** [great-lakes/project-egypt#8]
- Following Issue #6 & #7  
- Link Travis to blob container & CDN so that any updates to the github repo update static site in the blob container
- Use this [link](https://blog.lifeishao.com/2017/09/25/serving-hugo-on-azure-with-continuous-integration/) for reference. Note: it is a bit outdated but the linking is still possible)

**Comment by in4margaret** [comment]
Copied files from Travis build to Azure Blob and added CDN 
PR #41
