### ISSUE TITLE
Mockup UI of web page

### ISSUE THREAD

**Issue by gcrev93** [great-lakes/project-egypt#9]
- Work as a UI focused team to tackle this issue
Views:
- Home page View
- Generators View
- IoT Hubs View 
    -  Add a Hub
    -  View A Hub
    -  Add a Device
    -  Simulate a Device
    -  Monitor Device

You may add/change/ remove views based on judgement of what works best for the user

PLEASE review mockups with customer before implementation

Parent Issue: #22

**Comment by dwcares** [comment]
https://xd.adobe.com/view/2ce4d5fa-f18c-4e53-42e9-14766a13849e-5ad5/

GreatLakes1
